### ISSUE TITLE
OV2640 on Rpi 4B

### ISSUE THREAD

**Issue by canDry** [adafruit/Adafruit_CircuitPython_OV2640#19]
I'm hoping to directly connect an OV2640 (via the esp32 kaluga's separate ov2640 breakout board connected directly to rpi's gpio pins) to capture and process images on an Rpi 4B (not a pico or esp32).  
  
I've installed circuitpython (via blinka) and the adafruit ov2640 library, but that library calls imagecapture which is not on the rpi.  
  
Any guidance on how to get the ov2640 cam working would be most appreciated!

**Comment by jepler** [comment]
The imagecapture module is just in circuitpython on microcontrollers, not in blinka.
