### ISSUE TITLE
PICO example scales to 160x120 and uses test pattern

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_OV2640#7]
I'm having a few issues with the demo code for the ov2640 on a pico wtith the st7789 320x240 2inch display.
The demo has the test pattern enabled - is this intentional?
https://github.com/adafruit/Adafruit_CircuitPython_OV2640/blob/main/examples/ov2640_displayio_pico_st7789_2in.py#L67
I set it to False and it capture images ok now , but it si still scaling the image down to 160x120
```

Adafruit CircuitPython 7.0.0-alpha.4-132-gce7301527 on 2021-07-20; Raspberry Pi Pico with rp2040
>>> import ov2640_test
320 240 160 120

```
this is printed here 
https://github.com/adafruit/Adafruit_CircuitPython_OV2640/blob/main/examples/ov2640_displayio_pico_st7789_2in.py#L70

**Comment by jerryneedell** [comment]
This may be related to this:
https://github.com/adafruit/Adafruit_CircuitPython_OV2640/blob/main/examples/ov2640_displayio_pico_st7789_2in.py#L66
QQVGA is 160x120
but if I change this to QVGA (320x240) I get memory allocation errors

**Comment by jepler** [comment]
Yep, I bet it's due to memory limits that I lowered the resolution.

Would be happy to take a pull request to _comment out_ the test pattern mode by default.

**Comment by jerryneedell** [comment]
> Yep, I bet it's due to memory limits that I lowered the resolution.
> 
> Would be happy to take a pull request to _comment out_ the test pattern mode by default.

done in #8

**Comment by jerryneedell** [comment]
@jepler should this be closed? Is the anything that can be done about the limitation on the image size?

**Comment by jepler** [comment]
I think the resolution limitation is necessary at this point, so let's close this up.
